apiVersion: apps/v1
kind: Deployment

metadata:
  name: payment-service
  namespace: techstore

spec:
  replicas: 2

  selector:
    matchLabels:
      app: payment-service

  template:
    metadata:
      labels:
        app: payment-service

    spec:
      enableServiceLinks: false
      containers:
        - name: payment-service
          image: techstore-microservices-payment-service:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 8083

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/payment_db

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092

            - name: SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL
              value: http://schema-registry:8081


            - name: JAVA_TOOL_OPTIONS
              value: "-Dorg.apache.avro.SERIALIZABLE_PACKAGES=com.techstore.kafka"