{
  "type": "record",
  "name": "CreatePaymentRequested",
  "namespace": "com.techstore.kafka.order",
  "fields": [
    {
      "name": "eventId",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    },
    {
      "name": "orderId",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    },
    {
      "name": "reservationId",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    },
    {
      "name": "amount",
      "type": {
        "type": "bytes",
        "logicalType": "decimal",
        "precision": 19,
        "scale": 2
      }
    },
    {
      "name": "paymentMethodId",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    }
  ]
}