{
  "type": "record",
  "name": "CreateReservationRequested",
  "namespace": "com.techstore.kafka.order",
  "fields": [
    {
      "name": "eventId",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    },
    {
      "name": "orderId",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    },
    {
      "name": "expiresAt",
      "type": {
        "type": "long",
        "logicalType": "local-timestamp-millis"
      }
    },
    {
      "name": "items",
      "type": {
        "type": "array",
        "items": {
          "type": "record",
          "name": "ReservationItemRequested",
          "fields": [
            {
              "name": "productId",
              "type": {
                "type": "string",
                "logicalType": "uuid"
              }
            },
            {
              "name": "quantity",
              "type": "long"
            }
          ]
        }
      }
    }
  ]
}
