{
  "type": "record",
  "name": "CreatePaymentCompleted",
  "namespace": "com.techstore.kafka.payment",
  "fields": [
    {
      "name": "eventId",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    },
    {
      "name": "paymentId",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    },
    {
      "name": "orderId",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    },
    {
      "name": "reservationId",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    },
    {
      "name": "status",
      "type": {
        "type": "enum",
        "name": "PaymentStatus",
        "symbols": [
          "PENDING",
          "SUCCEEDED",
          "FAILED",
          "CANCELLED",
          "CANCELLING",
          "CONFIRMING"
        ]
      }
    },
    {
      "name": "paymentMethodId",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    }
  ]
}